sudo: required
services:
  - docker
before_install:
  - docker build -t hexy1620/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true hexy1620/docker-react npm run test 
language: generic